### ISSUE TITLE
SSH key instance does not update when using key_generate with overwrite true

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_core#10]
*Issue migrated from [https://api.github.com/repos/Jumpscale/core9/issues/236](), opened by @chrisvdg*

I'm creating a key using the sshkey client and running it again and find that the `pubkey` and `privkey` properties of the key stay the same
![image](https://user-images.githubusercontent.com/23582741/41423749-748ea0ba-6ffc-11e8-83c7-67d69005b4ce.png)

While in reality, new keys were generated on that path
![image](https://user-images.githubusercontent.com/23582741/41423833-ae3087e8-6ffc-11e8-88eb-03531ed498f8.png)

I expected the key instance returned in the second `key_generate` call to contain those newly generated keys

**Comment by PeterNashaat** [comment]
- Issue Verified :-

![image](https://user-images.githubusercontent.com/13523434/44002739-1adaadf0-9e48-11e8-88eb-47e3f22def08.png)

jumpscale_core : commit adbcb6425a9320b8b742bf4c243d1518913dd884
jumpscale_lib : commit 8a2ce89180e37734bb5cd740f1abd6e6367bcb4c
jumpscale_prefab : commit 418e2d80afff671669f6529202f0a139afca6d44
