### ISSUE TITLE
Bug: paramiko losing ssh-agent

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/jumpscale_core#135]
Getting a lot of these errors when running a script with a js_shell open, but sometimes without it too.

The script is used to setup services on the nodes in the Bancadati project, so getting a lot of zrobot clients and I have around 315 zrobot instances saved in the configmanager.

![image](https://user-images.githubusercontent.com/23582741/46076622-60e5f480-c18e-11e8-88d1-3c21aefb1388.png)

js_core is at commit 28515efa893162cfc08cc4e259bc268a4c48ef4d

**Comment by rkhamis** [comment]
@chrisvdg can you verify that this issue is resolved with https://github.com/threefoldtech/jumpscale_core/commit/951990e2863aa3f4227abb91f4c0d46b79dcd5d1

**Comment by chrisvdg** [comment]
@rkhamis , yep, seems to have fixed it!

**Comment by chrisvdg** [comment]
@rkhamis , confirmed that I don't get this issue anymore with provided commit!
