### ISSUE TITLE
ZDB backend generates massive amount of data on zdb

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/jumpscale_core#143]
For testing zdb I've set  up a container and installed JS on it and configured a zdb backend.

The zdb is installed on Bancadati and replicates the data over the 3 controller using syncthing
After looking at it a day after, the interface of one of the controllers seem to be freezing all the time.

This might be caused by syncthing trying to replicate the massive amounts of zdb backend files that is generated by the configmanager just sitting there idle with 1 test client installed.
Looking at the size of the backend, the zdb data dir was 250MB big and the index dir was slightly less than that.

The configmanager was using the `default` namespace but was the only one using that

**Comment by chrisvdg** [comment]
Yes, that is correct, I currently don't have the data anymore as I reset the zdb and syncthing services as to not disrupt the controllers and other services too much, but will try again and post more details if it happens again

**Comment by maxux** [comment]
I guess a lot of small changes occurs ?

**Comment by zaibon** [comment]
yeah but this is not logic that anything change if he has a single client. It should actually be one single write and then only reads. If we have lots of write, then the code is pretty bad. 
@xmonader can you explain the data flow and how the config manager deals with this ?

**Comment by xmonader** [comment]
@chrisvdg I'm not sure how to enable file logs anymore in jumpscale, but having it would haven been valuable 


only places where save operations happen 
- on configuring client
- on initializing a client  with data that differs from the old data (toml fancydumps might be failing and saving everytime, but even if you only initialize the client only once)
-  on explicit request to save or data change.

https://github.com/threefoldtech/jumpscale_core/blob/development/Jumpscale/tools/configmanager/JSBaseClassConfig.py#L91

 if there's explicit request to save or change in data  (check .save() calls)
https://github.com/threefoldtech/jumpscale_core/blob/development/Jumpscale/tools/configmanager/DbConfig.py

And the only other save is on `creation` of dbconfig
https://github.com/threefoldtech/jumpscale_core/blob/development/Jumpscale/tools/configmanager/DbConfig.py#L191


Also, can you make sure that you configure it to use another namespace to make it's isolated?

**Comment by maxux** [comment]
If this happens again, please send me index and data file for inspection

**Comment by chrisvdg** [comment]
Not able to reproduce overnight.

Might be that I didn't clean up properly from previous tests and syncthing replicated the data over all the nodes again.

Closing this issue, will reopen when I'm able to reproduce it again.
