### ISSUE TITLE
Cannot run install.sh as non-root, non-root cannot open js_shell

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/jumpscale_core#149]
#### Installation information

- jumpscale version: 9.6.0
- operating system: Ubuntu 18.04

#### Detailed description
Installation was only possible when adding "sudo bash -c" to the installation command, however after installation the js_shell is only available to the root user. Doesnt seem like desired behaviour

#### Steps to reproduce
Install using sudo on Ubuntu 18

**Comment by zaibon** [comment]
this is expect behavior
