### ISSUE TITLE
Services dissapear on robot using zdb backend

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/jumpscale_core#150]
For the bancadati project I set the nodes to have a zdb backend for the node robots.
I installed the monitoring and networking services needed on them and then wiped and reset the nodes (not the zdb) as the vm's on the nodes were still running..

Checking back on them later I noticed I couldn't see any services anymore other than the public `_node_capacity` service.

Trying to create the services again errors saying they already exist.
Trying to get the keys from services and adding them to the client (using https://gist.github.com/zaibon/5ed92fb7e9414987eb7c1c192dd676b7) did not make me see the services.
And getting the god token returns nothing
![image](https://user-images.githubusercontent.com/23582741/48951875-73876a80-ef40-11e8-85de-bda96487ac8f.png)

I can create new services and they do show up. Even after a normal reboot.

Can replicate this by wiping the disks of the node, rebooting it and set zdb backend again.

**Comment by chrisvdg** [comment]
So zdb backend can't handle when the disks are wiped, not sure if that's something we need to support

**Comment by zaibon** [comment]
zdb backend is not supported anymore.
