### ISSUE TITLE
Schema cleanup

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/jumpscale_core#157]
- [x] Code clean up
- [x] Documentation
- [x]  Test coverage

**Comment by BolaNasr** [comment]
https://github.com/threefoldtech/jumpscale_core/pull/161

**Comment by BolaNasr** [comment]
Documentation : [docs](https://github.com/threefoldtech/digital_me/tree/development_960/docs/schema)
Test coverage : [Tests](https://github.com/threefoldtech/jumpscale_core/tree/development_960_schema_cleanup/Jumpscale/data/schema/tests)
