### ISSUE TITLE
fix Schema Types 

### ISSUE THREAD

**Issue by BolaNasr** [threefoldtech/jumpscale_core#164]
- [x]  Bytes ( toHR , toml_string_get )

- [ ]  Object

- [ ]  JsObject 

- [ ] Json 

Those types need to fix because some of functions in types class NOT Implemented yet
and some types incorrect implementation

**Comment by ranatrk** [comment]
**Commit :** https://github.com/threefoldtech/jumpscale_core/commit/7904fdefff031f56a0fef3ea68ac1987cf0548aa

**Comment by ranatrk** [comment]
https://github.com/threefoldtech/jumpscale_core/commit/084feb3e8a7e8be16092b1f0be43dfa273836108

**Comment by zaibon** [comment]
moved to jsx
