### ISSUE TITLE
ZOS JS cmdline

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_core#167]
Create ZOS command line with click in jumpscale commands directory

js_zos should mimic same arguments (if possible) of the existing zos client

 - (for now just call the zos client)
 - use j.tools.zos or zos sal where relevant

**Comment by zaibon** [comment]
So decision has been taken ? Cause discussion about this is still open: https://github.com/threefoldtech/home/issues/72 . Can you please comment and make #72 the story for this issue.

Also regarding `js_zos should mimic same arguments (if possible) of the existing zos client`
I agree we should give the same feelings, but there a lot that can be improved in the UX of the current zos.

Having proper sub command group is one thing that I really would love to have. Cause right now have just a long flat list of command is really not user friendly and makes it hard to properly evolve.

So before rushing into code, I want to have some design done here to make things better then they were

**Comment by xmonader** [comment]
@rkhamis @zaibon on what bases that decision was taken?

**Comment by rkhamis** [comment]
I thought @despiegk discussed this with you two. He told me this is needed. I must've missed the other open discussion.

please also see my [comment](https://github.com/threefoldtech/home/issues/72#issuecomment-448228053)
