### ISSUE TITLE
jumpscale.py placed in location that violates LSB FSH

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#26]
https://wiki.linuxfoundation.org/lsb/fhs

the rules for filesystem hierarchies have been created for very specific
reasons, so that when people collaborate on a system, their expectations
are not completely broken.

jumpscale.py, when run from the developer mode (which needs to be the
default), *must* be installed in /usr/local/lib/pythonN.N/dist-packages

*only* when the software is to be deployed in PRODUCTION (that being
via a package manager, 0-robot probably qualifying for such) is the
installation permitted to be carried out in /usr/lib/*

this turned out to be extremely important and wasted considerable time,
as the installation of 0-robot turned out to have a critical dependency
on jumpscale.py being installed... which it did not, as it was a new install.

searches and investigations showed that "import jumpscale" from setup.py
was failing, yet there was absolutely no presence of a python module
"jumpscale" in /usr/local/lib/python3.5/dist-packages

only after MODIFYING the setup.py so that installation succeeded could an
strace be run which showed that jumpscale.py existed...
... in /usr/lib/python3.5/dist-packages.

**Comment by delandtj** [comment]
the correct way to do this is to cut/paste the code from a setup.py file (from setuptools import ....) and to use *exactly* that method.  actually creating a setup.py which goes into the same location as the auto-generated jumpscale.py and exec'ing "python3 setup.py install" may not be strictly necessary: it should be possible to get away with literally using "from setuptools import ...." and calling the setup() function with the location of the auto-generated jumpscale.py.

however... this begs the question, why is the jumpscale.py being created in the first place instead of adding in /opt/core/github/threefoldtech/* entries to sys.path when needed?

https://stackoverflow.com/questions/15109548/set-pythonpath-before-import-statements

**Comment by zaibon** [comment]
> however... this begs the question, why is the jumpscale.py being created in the first place instead of adding in /opt/core/github/threefoldtech/* entries to sys.path when needed?

As far as I understand this is done like this to allow to have the jumspcale shell and walk the all tree of module using only `j` a starting point.

But maybe your technic is cleaner and allow the same

**Comment by delandtj** [comment]
there's a way to patch sys.path to include say /opt/code/github/xxx and /opt/code/github/yyyy literally at the beginning of the module, which then picks up the imports dynamically behind the scenes, so that the code dropped into jumpscale.py looks "clean"... and remains static (not auto-generated).  i'll try to work on that today.
