### ISSUE TITLE
side-effects of instantiating electrum class

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#38]
apparently if the command below has not been run (which it hasn't, and hasn't been auto-detected as not being run, and so isn't sorted out automatically), it's not possible to instantiate the Electrum class.
 
```
Error: could not find paymentrequest_pb2.py. Create it with 'protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto'
```

**Comment by delandtj** [comment]
apparently the following says where the command has to be run:
https://github.com/fyookball/keys-n-hashes/issues/10

**Comment by delandtj** [comment]
https://github.com/spesmilo/electrum
sudo apt-get install protobuf-compiler
protoc --proto_path=electrum --python_out=electrum electrum/paymentrequest.proto

**Comment by ahussein** [comment]
What are you trying to do? Electrum class shouldn't be instantiated by
users. It's used as an embedded library and our j.clients.elecrum hook
should be used instead.

**Comment by delandtj** [comment]
i am creating a dynamic variant of jumpscale.py that can entirely replace the need for the static version.

in order to do so it is required to instantiate every single class object across absolutely every single module in absolutely every single file that is ever to be imported.

therefore they all need to work... and they don't.  many of the class instances (with no parameters) have severe side-effects.  this is one of them.  i've added a hack-work-around to the install.sh script that i am maintaining, which generates the file.
