### ISSUE TITLE
schema for numeric type is not working

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscale_core#75]
![image](https://user-images.githubusercontent.com/6021844/44116919-1b42f8b2-a012-11e8-9111-ffa3ce8758a7.png)

needs to be 6/7 bytes no string

**Comment by delandtj** [comment]
sorted - the detection for int/float was completely broken (and under certain circumstances could have caused exceptions).  added a proper float detection, and some unit tests: works fine now.

https://github.com/threefoldtech/jumpscale_core/commit/28c7c061afe125678ef268538022733099a19c6f

**Comment by delandtj** [comment]
it's still not going to be possible to store 10.50 or 10.23 or 5.89 as anything other than a float: that's definitely going to have to go into 8 bytes (as a double).  unless we add and distinguish two different types of float: IEEE754 single-precision (4 bytes) and IEEE754 double-precision (2 bytes).  it *may* also be possible to add IEEE754 half-precision (2 bytes) however that's getting complicated as it would need to be emulated in software: python does not have support for the half-precision floating-point type.  it would however get very high compression for floating-point numbers in the range +/-2047.
