### ISSUE TITLE
New alert manager creates a hard dependencies on digital me

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscale_core#78]
See these two lines:
https://github.com/threefoldtech/jumpscale_core/blob/ed63d0c8afac363047bec84a6f91e8dd33343648/Jumpscale/errorhandling/AlertHandler.py#L24-L25

So in order to work, this requires to have digital me installed. 
It seems to me that the schema modules should be extracted from digital me and move into the core.

**Comment by despiegk** [comment]
why is this a bug?

if alerthandler not called it will not throw an error?
alertmanager can only be used in DM context

is there another bug where this gets automatically called?

![image](https://user-images.githubusercontent.com/6021844/44384930-2c8f7080-a51e-11e8-9f06-ac23321a0510.png)

should make sure its not issue

**Comment by zaibon** [comment]
0-robot used to rely on the ECO of jumpscale to handle exceptions and allow to store and share exception that happened in tasks.
Since ECO are no more, I replace it with the alerthandler. So now 0-robot depend on digital me too.
If that is acceptable for you, just close this one, but having to depend on a full code base for just package of 3 files seems strange to me

**Comment by despiegk** [comment]
there is a strategy behind, lets discuss, for now lets close
