### ISSUE TITLE
new exceptions API completely breaks existing code, causing development to cease

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#81]
commit 3d8adac53 changed the exceptions API.  this is the result:

```
  File "/home/src/jumpscale_core/Jumpscale/tools/executor/ExecutorBase.py", line 502, in dir_paths
    return self.state.configGet('dirs')
  File "/home/src/jumpscale_core/Jumpscale/core/State.py", line 144, in configGet
    path=self.configJSPath)
  File "/home/src/jumpscale_core/Jumpscale/core/State.py", line 182, in _get
    (key, self), level=1, source="", tags="", msgpub="")
TypeError: __init__() got an unexpected keyword argument 'source'

```

a change to the exceptions API has been made without providing a means to warn people that code needs to move to the new API.

now all code - including third party code - breaks.

**Comment by zaibon** [comment]
Yep I just saw this one too, this pretty sever since I bet we can find this kind of construct all over the place :-/

**Comment by zaibon** [comment]
I'll already do a search and replace of the most common one I found.

**Comment by delandtj** [comment]
zaibon can you please also do the exact same thing in the development_dynamic branch otherwise i have to do that as well.

**Comment by delandtj** [comment]
commit 7162818a - comment out error escalation in JSLogger.error and JSLogger.critical for now

**Comment by delandtj** [comment]
zaibon, see commit 485dd:

```
commit 485dd227d8eb48d15b1fdb77ba8c905ef18efdf7
Author: Jan DeLandt <jan@bettertoken.com>
Date:   Thu Aug 23 13:13:09 2018 +0100

    issue #81 - putting arguments back into exceptions API
    
    removal of arguments from a commonly-used API is an absolute sure-fire
    guaranteed way to cause complete absolute chaos, and for all development
    work to cease until absolutely all code is modified to use the new API.
    
    as a "best engineering practices" workaround, the parameters have
    been REINSTATED, and, if they are ever used, a logging "error"
    is actioned that will, due to the high level, tell people that they
    have code to fix...
    
    ... however at least the code will keep working

```

**Comment by zaibon** [comment]
> zaibon can you please also do the exact same thing in the development_dynamic branch otherwise i have to do that as well.

sure thing, you have that branch on core, lib and prefab ?

**Comment by delandtj** [comment]
> sure thing, you have that branch on core, lib and prefab ?

yes, they're all there.  thx man.

**Comment by delandtj** [comment]
zaibon: you *can* run the unit tests, as follows:
```
# python3 setup.py test -s tests.jumpscale_test
```
they DO now get isolated so that any damage caused by one unit test to the config file does not destroy the main config file, HOWEVER, that does NOT stop the unit test(s) from e.g. doing "rm -fr Model/Capnp/.... etc".

so you will need to do a "git reset --hard" for now to get those files back (sigh) - i'm endeavouring to track down which unit test is damaging the files... and disabling it (with a bugreport to track it).

**Comment by delandtj** [comment]
zaibon: commit c048ba82220 looks great.  thanks.

**Comment by zaibon** [comment]
can I just checkout and dynamic branch and run the test? or is there a special way I need to install after checking out the branch ?

**Comment by delandtj** [comment]
make sure to delete jumpscale.py from /usr/lib/python3/dist-packages is the main thing.  if you're in a separate chroot there's nothing special to do at all.
