### ISSUE TITLE
ExecutorSSH and ExecutorLocal are not following the same timeout behaviour

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscale_core#9]
*Issue migrated from [https://api.github.com/repos/Jumpscale/core9/issues/238](), opened by @ashraffouda*

#### Installation information

- jumpscale version: development
- operating system: ubuntu 16.04

#### Detailed description
ExecutorSSh defines timeout parameter in its execute method and it is not used at any line of its code although ExecutorLocal uses this and this cause some prefab processes are timedout if u r using the local executor although they are working with ssh executor

**Comment by PeterNashaat** [comment]
issue verified 

jumpscale_core : commit adbcb6425a9320b8b742bf4c243d1518913dd884
jumpscale_lib : commit 8a2ce89180e37734bb5cd740f1abd6e6367bcb4c
jumpscale_prefab : commit 418e2d80afff671669f6529202f0a139afca6d44
